name: wine-platform-runtime-core22
version: v1.0
summary: wine platform runtime snap it provides WINE liberies for WINE
description: |
 This snap provides a WINE runtime liberies via content sharing to be used by other snaps that are using WINE.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
    build-for: amd64
base: core22
compression: lzo
assumes:
  - snapd2.55.4

lint:
  # Snapcraft's `ldd` lint can't handle 32-bit things,
  # So just make it quiet and also make builds a surprising amount faster
  ignore:
    - library:
        - lib/i386-linux-gnu/**
        - usr/lib/i386-linux-gnu/**
        - lib32/**
        - usr/lib32/**

slots:
  wine-runtime-c22:
    interface: content
    source:
      read:
      - $SNAP/bin
      - $SNAP/etc
      - $SNAP/lib
      - $SNAP/usr

package-repositories:
  - type: apt
    architectures: [i386,amd64]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    key-server: keyserver.ubuntu.com
    formats: [deb]
    components: [main, multiverse, universe, restricted]
    suites: [jammy]
    url: https://archive.ubuntu.com/ubuntu

parts:

  wine-runtime:
    plugin: nil
    stage-packages:
      - libasound2
      - libasound2-plugins
      - libavcodec58
      - libdrm-common
      - libgphoto2-6
      - libgstreamer-plugins-base1.0-0
      - libgcrypt20
      - locales-all
      - libldap-2.5-0
      - libncurses5
      - libopenal1
      - libpcap0.8
      - libpulse0
      - libudev1
      - libxext6
      - libxml2
      - libcapi20-3
      - libcups2
      - libcanberra-gtk-module
      - libdbus-1-3
      - libfontconfig1
      - libfreetype6
      - libgl1-mesa-glx
      - libgl1-mesa-dri
      - libglu1-mesa
      - libgnutls30
      - libgssapi-krb5-2
      - libodbc1
      - libosmesa6
      - libsane1
      - libsdl2-2.0-0
      - libv4l-0
      - libvulkan1
      - libxcomposite1
      - libxcursor1
      - libxcb-dri3-0
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libxxf86vm1
      - libvkd3d1
      - ocl-icd-libopencl1
      - winbind
      - samba-libs
      - mesa-va-drivers
      - mesa-vdpau-drivers
      - mesa-vulkan-drivers
      - zlib1g
      - binutils
      - util-linux
      - p7zip-full
      - mesa-utils
      - vulkan-tools
      - libpci3
      - xdg-utils
      - xdg-user-dirs
      - fontconfig-config
      - pciutils
      - lsof
      - va-driver-all
      - va-driver
      - on amd64:
        - libasound2:i386
        - libasound2-plugins:i386
        - libavcodec58:i386
        - libgphoto2-6:i386
        - libgstreamer-plugins-base1.0-0:i386
        - libgcrypt20:i386
        - locales-all:i386
        - libldap-2.5-0:i386
        - libncurses5:i386
        - libopenal1:i386
        - libpcap0.8:i386
        - libpulse0:i386
        - libudev1:i386
        - libxext6:i386
        - libxml2:i386
        - libcapi20-3:i386
        - libcups2:i386
        - libcanberra-gtk-module:i386
        - libdbus-1-3:i386
        - libfontconfig1:i386
        - libfreetype6:i386
        - libgl1-mesa-glx:i386
        - libgl1-mesa-dri:i386
        - libglu1-mesa:i386
        - libgnutls30:i386
        - libgssapi-krb5-2:i386
        - libodbc1:i386
        - libosmesa6:i386
        - libsane:i386
        - libsdl2-2.0-0:i386
        - libv4l-0:i386
        - libvulkan1:i386
        - libxcomposite1:i386
        - libxcursor1:i386
        - libxcb-dri3-0:i386
        - libxfixes3:i386
        - libxi6:i386
        - libxinerama1:i386
        - libxrandr2:i386
        - libxrender1:i386
        - libxxf86vm1:i386
        - libvkd3d1:i386
        - mesa-va-drivers:i386
        - mesa-vdpau-drivers:i386
        - mesa-vulkan-drivers:i386
        - ocl-icd-libopencl1:i386
        - winbind:i386
        - samba-libs:i386
        - va-driver-all:i386
        - va-driver:i386
        - zlib1g:i386
    override-build: |
      craftctl default
      sed -i 's|/usr|$SNAP/wine-runtime/usr|' $CRAFT_PART_INSTALL/usr/bin/7z
      sed -i 's|/usr|$SNAP/wine-runtime/usr|' $CRAFT_PART_INSTALL/usr/bin/7za
      sed -i 's|/usr|$SNAP/wine-runtime/usr|' $CRAFT_PART_INSTALL/usr/bin/7zr
      rm -rf $CRAFT_PART_INSTALL/etc/init
      rm -rf $CRAFT_PART_INSTALL/etc/init.d
      rm -rf $CRAFT_PART_INSTALL/etc/logrotate.d
      rm -rf $CRAFT_PART_INSTALL/usr/share/apps
      rm -rf $CRAFT_PART_INSTALL/usr/share/applications
      rm -rf $CRAFT_PART_INSTALL/usr/share/bug
      rm -rf $CRAFT_PART_INSTALL/usr/share/doc
      rm -rf $CRAFT_PART_INSTALL/usr/share/doc-base
      rm -rf $CRAFT_PART_INSTALL/usr/share/debhelper
      rm -rf $CRAFT_PART_INSTALL/usr/share/lintian
      rm -rf $CRAFT_PART_INSTALL/usr/share/man
      rm -rf $CRAFT_PART_INSTALL/usr/share/pixmaps
      rm -rf $CRAFT_PART_INSTALL/usr/share/pkgconfig

  wine-platform-runtime:
    plugin: dump
    source: snap/local/scripts
    organize:
      'zenity': bin/
      'wprfile': bin/
      'nlpfile': bin/
    build-packages:
      - libglib2.0-0
      - libxml2
      - libpsl5
    stage-packages:
      - cabextract         # winetricks
      - libgdk-pixbuf2.0-0 # yad
      - libgtk-3-0         # yad
      - libnotify4         # yad
      - libnotify-bin      # sommelier
      - perl-base          # winetricks
      - shared-mime-info
      - unzip              # winetricks
      - wget               # winetricks
      - x11-xserver-utils  # sommelier
      - yad                # winetricks
      - jq                 # desktop-launch
    override-build: |
      craftctl default
      touch $CRAFT_PART_INSTALL/wprfile
      touch $CRAFT_PART_INSTALL/nlpfile
      update-mime-database $CRAFT_PART_INSTALL/usr/share/mime
      rm -rf $CRAFT_PART_INSTALL/etc/init
      rm -rf $CRAFT_PART_INSTALL/etc/init.d
      rm -rf $CRAFT_PART_INSTALL/etc/logrotate.d
      rm -rf $CRAFT_PART_INSTALL/usr/bin/fc-*
      rm -rf $CRAFT_PART_INSTALL/usr/bin/gtk-*
      rm -rf $CRAFT_PART_INSTALL/usr/lib/dconf/dconf-service
      rm -rf $CRAFT_PART_INSTALL/usr/lib/glib-networking/glib-pacrunner
      rm -rf $CRAFT_PART_INSTALL/usr/share/GConf
      rm -rf $CRAFT_PART_INSTALL/usr/share/aclocal
      rm -rf $CRAFT_PART_INSTALL/usr/share/apport
      rm -rf $CRAFT_PART_INSTALL/usr/share/apps
      rm -rf $CRAFT_PART_INSTALL/usr/share/bash-completion
      rm -rf $CRAFT_PART_INSTALL/usr/share/bug
      rm -rf $CRAFT_PART_INSTALL/usr/share/debhelper
      rm -rf $CRAFT_PART_INSTALL/usr/share/doc
      rm -rf $CRAFT_PART_INSTALL/usr/share/doc-base
      rm -rf $CRAFT_PART_INSTALL/usr/share/icons/Adwaita
      rm -rf $CRAFT_PART_INSTALL/usr/share/icons/Humanity*
      rm -rf $CRAFT_PART_INSTALL/usr/share/icons/LoginIcons
      rm -rf $CRAFT_PART_INSTALL/usr/share/icons/ubuntu-mono*
      rm -rf $CRAFT_PART_INSTALL/usr/share/info
      rm -rf $CRAFT_PART_INSTALL/usr/share/kde4
      rm -rf $CRAFT_PART_INSTALL/usr/share/lintian
      rm -rf $CRAFT_PART_INSTALL/usr/share/menu
      rm -rf $CRAFT_PART_INSTALL/usr/share/man
      rm -rf $CRAFT_PART_INSTALL/usr/share/perl5
      rm -rf $CRAFT_PART_INSTALL/usr/share/pixmaps
      rm -rf $CRAFT_PART_INSTALL/usr/share/pkgconfig
    after:
      - wine-runtime

  fixup-winetricks:
    plugin: nil
    after: [wine-platform-runtime]
    organize:
      'winetricks': bin/
    override-build: |
      wget -nvc "https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks" -O $CRAFT_PART_INSTALL/winetricks
      chmod +x $CRAFT_PART_INSTALL/winetricks

  fixup-vulkan-icd-paths:
    plugin: nil
    after: [fixup-winetricks]
    override-build: |
      sed -i -E 's,(^.+"library_path": ")/.*/,\1,' $CRAFT_STAGE/usr/share/vulkan/icd.d/*.json
      wget -nvc https://gist.github.com/mmtrt/8d1a2b9eb33429feb0197ec46b0acdf4/raw/a8082e47f3a9c2a4f5acd8cf81da6ec62c00d5fc/nvidia_icd.json -P $CRAFT_PART_INSTALL/usr/share/vulkan/icd.d
